### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Ily1606** [Laratypes/Laratype#1]
- [ ] Core concepts
   - [ ] Support type safe Restful API
   - [ ] Support JSON schema
- [ ] App
   - [ ] Configs
      - [x] App 
      - [x] Database
      - [ ] Queue
      - [x] Auth
      - [ ] Broadcast
      - [ ] Cache
      - [ ] CORS
      - [x] Logging
      - [ ] Mail
   - [x] Bootstraps
      - [x] Service providers
   - [ ] Console
      - [ ] Built-in commands (sauf package)
         - [ ] Dev Server Command
            - [x] Starting command
            - [ ] Support HMR
         - [x] Production Build Command
         - [x] Generating commands
      - [x] Integration commands (app commands)
   - [ ] HTTP
      - [ ] Route
        - [x] Route Option
        - [x] Model Binding
          - [x] Explicit Binding
          - [x] Implicit Binding
      - [ ] Router
      - [ ] Middleware
        - [x] Route middleware
        - [x] Support route group
        - [x] Support withoutMiddleware
      - [ ] FormRequest
         - [x] Support zod
         - [ ] Support i18n validation message 
      - [x] Controller
   - [ ] ORM
      - [x] Intergration TypeORM
   - [ ] File storage
      - [ ] Suport AWS S3
   - [ ] Localization
   - [ ] Process
   - [ ] Queues
   - [ ] Batch
     - [ ] Chaining
       - [ ] Allowing failure
     - [ ] Parallel
   - [ ] Security
     - [ ] Authentication 
       - [x] JWT
       - [ ] OAuth2
     - [ ] Authorization
        - [x] Gate
        - [x] Policy
   - [ ] Event
   - [ ] Listener
   - [ ] Broadcast
   - [ ] Mail
      -  [ ] Support mailer
      -  [ ] Support AWS SES
   - [ ] Schedule
      - [ ] Job schedule
      - [ ] Command schedule
   - [ ] Database
      - [ ] Migration 
      - [x] Factory
      - [x] Seeder
   - [ ] View
      - [ ] Support SPA
      - [ ] Support SSR
      - [ ] Support other frameworks
         - [ ] Vue.js
         - [ ] ReactJS
         - [ ] Svelte
   - [ ] Other
      - [x] Integration Vite for building development and production
      - [ ] Typesafe router name
 - [ ] Platform
   - [x] Nodejs
   - [x] Bun
   - [ ] Deno
   - [ ] EDGE
      - [ ] Cloudflare
      - [ ] Heroku
      - [ ] Vercel
